"use client";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useAuth } from "./AuthProvider";
export default function Navbar() {
  const { user, loading, logout } = useAuth(); const router = useRouter(); const handleLogout = async () => { await logout(); router.push("/"); };
  return <header className="sticky top-3 z-30 mx-auto mt-3 flex max-w-7xl items-center justify-between rounded-full border border-emerald-100 bg-white/95 px-4 py-3 shadow-sm backdrop-blur sm:px-5"><Link href="/" className="flex items-center gap-3" aria-label="Naik Foods home"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-emerald-600 font-bold text-white">N</span><span className="hidden sm:block"><b className="block text-slate-900">Naik Foods</b><small className="block text-[9px] uppercase tracking-[.2em] text-slate-500">Fresh & healthy</small></span></Link><nav className="hidden gap-5 text-sm font-medium text-slate-600 md:flex"><Link href="/">Home</Link><Link href="/shop">Shop</Link><Link href="/wishlist">Wishlist</Link><Link href="/cart">Cart</Link>{user && ["ADMIN", "SUPER_ADMIN", "STAFF"].includes(user.role) && <Link href="/admin">Admin</Link>}</nav><div className="flex items-center gap-2 text-sm">{loading ? null : user ? <><Link href="/profile" className="flex items-center gap-2 rounded-full px-2 py-1 text-slate-700 hover:bg-emerald-50">{user.avatar ? <img src={user.avatar} alt="" className="h-7 w-7 rounded-full object-cover" /> : <span className="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-100 font-semibold text-emerald-700">{user.name?.[0]?.toUpperCase()}</span>}<span className="hidden max-w-24 truncate sm:inline">{user.name}</span></Link><button onClick={handleLogout} className="rounded-full border border-slate-200 px-3 py-1.5 font-medium text-slate-700 hover:bg-slate-50">Logout</button></> : <><Link href="/login" className="rounded-full border border-slate-200 px-3 py-1.5 font-medium text-slate-700">Login</Link><Link href="/register" className="hidden rounded-full bg-emerald-600 px-3 py-1.5 font-semibold text-white sm:inline">Register</Link></>}</div></header>;
}
